
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: "ruby -v"
      - run: "gem install bundler"
      - run: "bundle install"
      - run: "echo hello world"
      
  test:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: "ruby -v"
      - run: "gem install bundler"
      - run: "bundle install"
      - run: "echo hello world"
    requires:
      - buid
    
    

