
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: gem install bundler -v 2.1.4
      - restore_cache: #here we look if key already exist if not then it will saved on save_cache
          key: v3-bundle-{{ checksum "Gemfile.lock" }}
      - run: "bundle install"
      - save_cache:
          key: v3-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle # this is path where our all gems are located aftre bundle install, we are storing our keys also ther
      - run: mkdir -p my-work-space # create workspce
      - run: echo "hello world" > my-work-space/echo_text # file echo text in my-work-space
      - persist_to_workspace:
          root: my-work-space # this is directory
          paths: 
            - echo_text  # file in directory
      
  test:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - restore_cache: #here we look if key already exist if not then it will saved on save_cache
          key: v3-bundle-{{ checksum "Gemfile.lock" }}
      - run: "bundle install"
      - save_cache:
          key: v3-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle # this is path where our all gems are located aftre bundle install, we are storing our keys also ther
      - run: "rspec test.rb"
      - attach_workspace:
          at: my-work-space
      - run: cat my-work-space/echo_text

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
    
    
    

