
version: 2.1

jobs:
  build:
    docker:
      image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run: "gem install bundler"
      - run: "bundle install"
      - run: "echo hello world" 
