
version: 2.1

jobs:
  build:
    working_directory: /first-circle-ci
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: "ruby -v"
      - run: "gem install bundler"
      - run: "bundle install"
      - run: "echo hello world"
      
  test:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - run: "ruby -v"
      - run: "bundle install"
      - run: "rspec test.rb"

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
    
    
    

