
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: "ruby -v"
      - run: "gem install bundler"
      - run: "bundle install"
      - run: "echo hello world"
      - run: "mkdir my-work-sapce" # create workspce
      - run: echo "hello world" > my-work-space/echo_text # file echo text in my-work-space
      - persist_to_workspace:
          root: my-work-space
          paths: 
            - echo_text
      
  test:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: "ruby -v"
      - run: "bundle install"
      - run: "rspec test.rb"
      - attach_workspace:
          at: my-work-spce
      - run: cat my-work-space/echo_text

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
    
    
    

