
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: "gem install bundler"
      - run: "bundle install"
      - run: "echo hello world" 
